name: Lint and Type Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 13 * * 5'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx next lint .
          --config .eslintrc.json
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload ESLint analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  typecheck:
    name: Run TypeScript type checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.3.0'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type check
        run: npm run typecheck

  - name: Create SARIF file for TypeScript
      if: failure()  # Запускаем только если проверка типов не прошла
      run: |
        echo '{
          "version": "2.1.0",
          "runs": [{
            "tool": {
              "driver": {
                "name": "TypeScript Type Check",
                "version": "1.0.0"
              }
            },
            "results": [{
              "ruleId": "typescript-check",
              "level": "error",
              "message": "TypeScript type checking failed",
              "locations": []
            }]
          }]
        }' > ts-results.sarif

      - name: Upload TypeScript analysis results to GitHub
        if: failure()  # Загрузка результатов только при наличии ошибок
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ts-results.sarif
          wait-for-processing: true
