name: Type Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 13 * * 5'

jobs:
  typecheck:
    name: Run TypeScript type checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.3.0'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type check
        run: npm run typecheck
